apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "yujian-platform.fullname" . }}-platform-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: platform-api
