apiVersion: v1
kind: Service
metadata:
  name: {{ include "yujian-platform.fullname" . }}-platform-api
spec:
  selector:
    app.kubernetes.io/component: platform-api
  ports:
    - name: http
      port: {{ .Values.service.platformApiPort }}
      targetPort: http
