apiVersion: v1
kind: Service
metadata:
  name: {{ include "yujian-platform.fullname" . }}-postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
